### PR TITLE
Update for Laravel 8

### PR DESCRIPTION
**Pull request by asbiin**

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks @asbiin! Would you mind using single pipe characters instead of double? I know their the same, but I try to align all of my packages with the same syntax.

**Comment by asbiin** [comment]
I think single pipe is deprecated, at least is not documented anymore https://getcomposer.org/doc/articles/versions.md#version-range

**Comment by stevebauman** [comment]
It's not documented, but it's supported:

https://github.com/composer/semver/blob/da7ce661431b17a71271cdf7f5437dc722133123/src/VersionParser.php#L254

It's still *very* common place -- even the Laravel framework uses it in their `composer.json` file:

https://github.com/laravel/framework/blob/257b95cde5f82df232688050e9b8a1e652d15a1e/composer.json#L22

Spatie:

https://github.com/spatie/laravel-medialibrary/blob/cb358477b411cf1f7392878bf72407a5f7082ea6/composer.json#L28-L33

**Comment by asbiin** [comment]
Fair enough! :+1:

**Comment by stevebauman** [comment]
Awesome, thanks! 👍

**Pull request merged**
