### PR TITLE
ipApiPro config fix

### PR DESCRIPTION
**Pull request by callumMcComisky**
api key can't be found using config('ip_api.token')

### CODE REVIEW

**Comment by stevebauman** [comment]
Ah jeez, 🤦‍♂ thanks for this!

**Comment by robertwstickets** [comment]
Whats the difference for this one? It seemed to work fine on my end.

**Comment by stevebauman** [comment]
@robertwstickets Really? This is the IpApiPro version, the configuration key was not suffixed properly before this patch. The only way this would have worked is if you set the key manually using:

```php
Config::set('ip_api.token', 'mytoken');
```

Or if you created an `ip_api.php` file inside your applications `config` directory:

```php
<?php

return ['token' => 'mytoken'];
```

**Comment by robertwstickets** [comment]
I set my key in the env file. with
 `IP_API_TOKEN = *MY KEY HERE* `
and in the location config
with 
```
 /*
    |--------------------------------------------------------------------------
    | IPInfo Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration for the IPInfo driver.
    |
    */

    'ipinfo' => [

	    'token' => 'MYKEY HERE',

    ],
```

**Comment by stevebauman** [comment]
That's the IpInfo driver, not IpAPi - they are different drivers for different resources:

https://github.com/stevebauman/location/blob/master/src/Drivers/IpApiPro.php

https://github.com/stevebauman/location/blob/master/src/Drivers/IpInfo.php

**Comment by robertwstickets** [comment]
My Mistake... :(

**Comment by stevebauman** [comment]
No problem! :smile:

**Pull request merged**
