### PR TITLE
Update MaxMind driver: Missing longitude.

### PR DESCRIPTION
**Pull request by dpgover**
I cannot edit this driver for Laravel 4. Github only let me change it on master.

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks!

**Comment by dpgover** [comment]
Can you push the change to a new 1.1.x tag? I'm still using Laravel 4 for my project (at least for a few weeks) and I need this to be able to deploy changes to the server.

Thanks and, if not, thanks anyway! :smile:

**Comment by stevebauman** [comment]
Yup absolutely, will be out in just a sec, thanks!

**Comment by dpgover** [comment]
Awesome!

Thanks.

**Comment by dpgover** [comment]
Sorry to bother you. Can you make a release for 1.3.x too?
Or are you planning on a release soon for other reasons?

**Comment by stevebauman** [comment]
No problem at all, and I just released v1.3.1, apologies for delay.

**Comment by dpgover** [comment]
Many many many thanks!

**Pull request merged**
