### PR TITLE
Add IP2Location.io Driver

### PR DESCRIPTION
**Pull request by ip2location**
Related to #147 .

### CODE REVIEW

**Comment by ip2location** [comment]
Hi @stevebauman ,

May I check what is the progress now?

**Comment by stevebauman** [comment]
Sorry for the late review on this @ip2location! Looks good to me, thanks for your contribution!

The test added in this PR is failing, can you fix it? Once fixed, I'll merge and deploy a new version 👍

**Comment by ip2location** [comment]
> Sorry for the late review on this @ip2location! Looks good to me, thanks for your contribution!
> 
> The test added in this PR is failing, can you fix it? Once fixed, I'll merge and deploy a new version 👍

Hi @stevebauman,

I have checked the error message, but looks like it is failing on Maxmind's driver, I'm not sure what I can do from my side.

**Comment by stevebauman** [comment]
Screenshot 2023-11-21 at 7 32 09 PM

**Comment by ip2location** [comment]
> Screenshot 2023-11-21 at 7 32 09 PM

Hi @stevebauman ,

I didn't noticed this on yesterday. I have pushed new fix for the failing test and the test case is passed on my side.

**Comment by stevebauman** [comment]
No worries, thanks for fixing it! 🙏

**Pull request merged**
